sonar.organization=dabo224
sonar.projectKey=dabo224_Nesten-Project
sonar.projectName=Nesten Project

# Sources analysées
sonar.sources=backend/src,frontend/src

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/.angular/**,\
  **/coverage/**,\
  **/prisma/**,\
  **/*.spec.ts,\
  **/environments/**

# Fichiers de test (backend Jest)
sonar.tests=backend/src
sonar.test.inclusions=**/*.test.js

# Couverture de code (rapport lcov généré par Jest)
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8
